apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: order-deployment
  selfLink: /apis/autoscaling/v1/namespaces/kumuluzee-blog/horizontalpodautoscalers/order-deployment
spec:
  maxReplicas: 4
  minReplicas: 1
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: order-deployment
  targetCPUUtilizationPercentage: 50
